import Link from "next/link";
import { BandBadge, ReviewBadge, bandLabel, buttonClass, fmtMiles, gapText } from "@/components/ui";
import type { Brief, Match, Project } from "@/lib/types";
import { PrintButton } from "./PrintButton";
import s from "./pair.module.css";

function FactIds({ ids, brief }: { ids: string[]; brief: Brief }) {
  return (
    <span className={s.factIds}>
      {ids.map((id) => {
        const fact = brief.facts?.find((f) => f.id === id);
        return (
          <code key={id} title={fact ? JSON.stringify(fact) : undefined}>
            {id}
          </code>
        );
      })}
    </span>
  );
}

function when(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : `${d.toISOString().slice(0, 16).replace("T", " ")} UTC`;
}

export function CoordinationCard({ m, a, b, brief }: { m: Match; a: Project | null; b: Project | null; brief: Brief | null }) {
  const name = (p: Project | null, key: string) => p?.name ?? key;
  return (
    <section className={s.card} aria-labelledby="card-title">
      <header className={s.cardHead}>
        <h2 id="card-title">Coordination card</h2>
        <div className={`${s.cardActions} no-print`}>
          <PrintButton />
          <a className={buttonClass} href={`/api/export?type=matches&view=${m.view}`} download>
            CSV ({m.view})
          </a>
          <Link className={buttonClass} href={`/impact?pair=${encodeURIComponent(m._id)}`}>
            Impact inputs →
          </Link>
        </div>
      </header>

      <h3>Deterministic facts</h3>
      <ul className={s.factList}>
        <li>
          Centers are <strong className="num">{fmtMiles(m.distance_mi)}</strong> apart (center-to-center, not a route;
          unrounded {m.distance_mi.toFixed(6)} mi), under the 25 mi overlap rule. <BandBadge band={m.band} />
        </li>
        <li>
          Planned in-service dates: {a?.in_service.raw ?? "not published"} ({name(a, m.a)}) and{" "}
          {b?.in_service.raw ?? "not published"} ({name(b, m.b)}): <strong className="num">{gapText(m.time_gap_days)}</strong>.
          {m.time_gap_days === null ? " No exact gap without two day-precision dates." : ""} An in-service date is a
          milestone, not a construction window.
        </li>
        <li>
          View <strong>{m.view}</strong> at analysis date <span className="num">{m.analysis_date}</span>
          {m.rank ? (
            <>
              ; priority rank <strong className="num">{m.rank}</strong> ({bandLabel(m.band)} band, then gap, then
              distance)
            </>
          ) : null}
          . <ReviewBadge state={m.review_state} />
        </li>
        <li className={s.muted}>
          Rules: <code>{m.rule_version}</code>, ranking <code>{m.rank_version}</code>.
        </li>
      </ul>

      <h3>Gemini brief</h3>
      {brief ? (
        <div className={s.brief}>
          <p className={s.aiLabel}>
            Generated by Gemini <code>{brief.model}</code> at {when(brief.generated_at)} · prompt{" "}
            <code>{brief.prompt_version}</code> · every statement cites fact ids from the inputs above.
          </p>
          <h4>Supported facts</h4>
          <ul>
            {brief.supported_facts.map((f, i) => (
              <li key={i}>
                {f.text} <FactIds ids={f.fact_ids} brief={brief} />
              </li>
            ))}
          </ul>
          <h4>Possible shared activities</h4>
          <ul>
            {brief.possible_shared_activities.map((f, i) => (
              <li key={i}>
                {f.text} <FactIds ids={f.fact_ids} brief={brief} />
              </li>
            ))}
          </ul>
          <h4>Open questions</h4>
          <ul>
            {brief.questions.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
          <h4>Limitations</h4>
          <ul>
            {brief.limitations.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </div>
      ) : (
        <p className={s.unknown}>Brief unavailable: no validated Gemini brief exists for this pair.</p>
      )}
    </section>
  );
}
